# Generated by Django 2.2 on 2019-04-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('message', models.CharField(help_text='message', max_length=250)),
            ],
            options={
                'ordering': ['sender', 'message'],
            },
        ),
    ]
