# Generated by Django 2.2 on 2019-04-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['s', 'm']},
        ),
        migrations.RenameField(
            model_name='mesa',
            old_name='message',
            new_name='m',
        ),
        migrations.RenameField(
            model_name='mesa',
            old_name='sender',
            new_name='s',
        ),
    ]
