# Generated by Django 2.2 on 2019-04-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0002_auto_20190427_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['sender', 'message']},
        ),
        migrations.RenameField(
            model_name='mesa',
            old_name='m',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='mesa',
            old_name='s',
            new_name='sender',
        ),
    ]
